#include "Application.h"
#include <GL/glew.h>      // Must be before glfw3.h
#include <GLFW/glfw3.h>
#include <imgui.h>
#include <imgui_impl_glfw.h>
#include <imgui_impl_opengl3.h>
#include "audio_processor.h"
#include "visualizer.h"
#include "ui_manager.h"
#include <iostream>

Application::Application() = default;

Application::~Application() {
    cleanup();
}

// --- Initialization Steps --- 

bool Application::initGLFW() {
    if (!glfwInit()) {
        std::cerr << "Failed to initialize GLFW" << std::endl;
        return false;
    }

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
#ifdef __APPLE__
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
#endif

    m_window = glfwCreateWindow(WINDOW_WIDTH, WINDOW_HEIGHT, "Audio Visualizer", NULL, NULL);
    if (!m_window) {
        std::cerr << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return false;
    }

    glfwMakeContextCurrent(m_window);
    glfwSwapInterval(1); // Enable vsync

    // Store 'this' pointer to access instance members in static callback
    glfwSetWindowUserPointer(m_window, this);
    glfwSetFramebufferSizeCallback(m_window, framebuffer_size_callback_static);

    return true;
}

bool Application::initGLEW() {
    glewExperimental = GL_TRUE;
    if (glewInit() != GLEW_OK) {
        std::cerr << "Failed to initialize GLEW" << std::endl;
        return false;
    }
    // Clear any errors generated by glewInit() (known issue)
    while(glGetError() != GL_NO_ERROR);
    return true;
}

bool Application::initImGui() {
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    // io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard; // Enable Keyboard Controls
    // io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;  // Enable Gamepad Controls
    // io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;   // Disable Docking for now
    // io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable; // Disable Multi-Viewport for now

    ImGui::StyleColorsDark();
    
    // Tweak styles when viewports are enabled
    ImGuiStyle& style = ImGui::GetStyle();
    // if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) { // Disable check for now
    //     style.WindowRounding = 0.0f;
    //     style.Colors[ImGuiCol_WindowBg].w = 1.0f;
    // }

    // Enhance control responsiveness and visibility (copied from old main.cpp)
    style.FrameRounding = 3.0f;
    style.GrabRounding = 3.0f;
    style.FrameBorderSize = 1.0f;
    style.GrabMinSize = 20.0f;
    style.ItemSpacing = ImVec2(8, 4);
    style.ItemInnerSpacing = ImVec2(4, 4);
    style.IndentSpacing = 12.0f;
    style.ScrollbarSize = 14.0f;
    style.WindowRounding = 4.0f;
    style.ChildRounding = 2.0f;
    style.PopupRounding = 2.0f;
    style.Alpha = 0.95f; // Slightly more opaque
    style.DisabledAlpha = 0.6f;
    style.Colors[ImGuiCol_SliderGrab] = ImVec4(0.8f, 0.8f, 0.8f, 0.9f);
    style.Colors[ImGuiCol_SliderGrabActive] = ImVec4(0.9f, 0.9f, 0.9f, 1.0f);
    style.Colors[ImGuiCol_FrameBgHovered] = ImVec4(0.3f, 0.3f, 0.3f, 0.9f);
    style.Colors[ImGuiCol_FrameBgActive] = ImVec4(0.4f, 0.4f, 0.4f, 0.9f);

    if (!ImGui_ImplGlfw_InitForOpenGL(m_window, true)) return false;
    if (!ImGui_ImplOpenGL3_Init("#version 330")) return false;

    return true;
}

bool Application::initModules() {
    m_audioProcessor = new AudioProcessor();
    if (!m_audioProcessor->initialize(SAMPLE_RATE, FRAMES_PER_BUFFER, NUM_CHANNELS)) {
        std::cerr << "Failed to initialize audio processor" << std::endl;
        return false;
    }

    int initialWidth, initialHeight;
    glfwGetFramebufferSize(m_window, &initialWidth, &initialHeight);
    m_visualizer = new Visualizer(*m_audioProcessor);
    if (!m_visualizer->initialize(initialWidth, initialHeight)) {
        std::cerr << "Failed to initialize visualizer" << std::endl;
        return false;
    }

    m_uiManager = new UIManager(*m_audioProcessor, *m_visualizer);
    // No specific init needed for UIManager currently

    return true;
}

// --- Main Initialization --- 

bool Application::initialize() {
    if (!initGLFW()) return false;
    if (!initGLEW()) return false;
    if (!initImGui()) return false;
    if (!initModules()) return false;
    return true;
}

// --- Main Loop --- 

void Application::run() {
    while (!glfwWindowShouldClose(m_window)) {
        glfwPollEvents();

        // Start the Dear ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // Get current framebuffer size for rendering viewport
        int display_w, display_h;
        glfwGetFramebufferSize(m_window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);

        // Clear the background
        glClearColor(0.1f, 0.1f, 0.12f, 1.0f); // Slightly darker blueish background
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        // Render UI using the manager
        m_uiManager->render(m_window);

        // Render main visualization
        m_visualizer->render();

        // Render Dear ImGui
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        // Update and Render additional Platform Windows (for docking/viewports)
        // ImGuiIO& io = ImGui::GetIO(); // Already got io above
        // if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) { // Disable check for now
        //     GLFWwindow* backup_current_context = glfwGetCurrentContext();
        //     ImGui::UpdatePlatformWindows();
        //     ImGui::RenderPlatformWindowsDefault();
        //     glfwMakeContextCurrent(backup_current_context);
        // }

        glfwSwapBuffers(m_window);
    }
}

// --- Cleanup --- 

void Application::cleanup() {
    // Cleanup ImGui
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    if (ImGui::GetCurrentContext()) { // Check if context exists before destroying
        ImGui::DestroyContext();
    }

    // Cleanup modules (delete allocated memory)
    delete m_uiManager;
    m_uiManager = nullptr;
    delete m_visualizer;
    m_visualizer = nullptr;
    delete m_audioProcessor;
    m_audioProcessor = nullptr;

    // Cleanup GLFW
    if (m_window) {
        glfwDestroyWindow(m_window);
        m_window = nullptr;
    }
    glfwTerminate();
}

// --- Callback Handling --- 

// Static callback function
void Application::framebuffer_size_callback_static(GLFWwindow* window, int width, int height) {
    // Retrieve the Application instance stored in the window's user pointer
    Application* app = static_cast<Application*>(glfwGetWindowUserPointer(window));
    if (app) {
        app->framebuffer_size_callback(width, height);
    }
}

// Instance member function to handle the resize
void Application::framebuffer_size_callback(int width, int height) {
    if (width > 0 && height > 0 && m_visualizer) {
        m_visualizer->resize(width, height);
    }
} 