#include "Application.h"
#include <GL/glew.h>      // Must be before glfw3.h
#include <GLFW/glfw3.h>
#include <imgui.h>
#include <imgui_impl_glfw.h>
#include <imgui_impl_opengl3.h>
#include "audio_processor.h"
#include "visualizer.h"
#include "ui_manager.h"
#include <iostream>
#include <nfd.h> // Include NFD header

Application::Application() = default;

Application::~Application() {
    cleanup();
}

// --- Initialization Steps --- 

bool Application::initGLFW() {
    if (!glfwInit()) {
        std::cerr << "Failed to initialize GLFW" << std::endl;
        return false;
    }

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
#ifdef __APPLE__
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
#endif

    glfwWindowHint(GLFW_OPENGL_DEBUG_CONTEXT, GLFW_TRUE);

    m_window = glfwCreateWindow(WINDOW_WIDTH, WINDOW_HEIGHT, "Audio Visualizer", NULL, NULL);
    if (!m_window) {
        std::cerr << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return false;
    }

    glfwMakeContextCurrent(m_window);
    if (!initGLEW()) { 
        std::cerr << "Failed to initialize GLEW after creating context." << std::endl;
        glfwTerminate(); // Clean up GLFW if GLEW fails
        return false;
    }

    // Enable Depth Testing and Face Culling for 3D
    glEnable(GL_DEPTH_TEST);
    glDepthFunc(GL_LEQUAL); // Standard depth comparison
    glEnable(GL_CULL_FACE); 
    glCullFace(GL_BACK); // Cull back-facing polygons
    glFrontFace(GL_CCW); // Define front-facing polygons as counter-clockwise

    glfwSwapInterval(1); // Enable vsync

    // Store 'this' pointer to access instance members in static callback
    glfwSetWindowUserPointer(m_window, this);
    glfwSetFramebufferSizeCallback(m_window, framebuffer_size_callback_static);
    glfwSetCursorPosCallback(m_window, cursor_position_callback_static);
    glfwSetMouseButtonCallback(m_window, mouse_button_callback_static);
    glfwSetScrollCallback(m_window, scroll_callback_static);

    return true;
}

bool Application::initGLEW() {
    glewExperimental = GL_TRUE;
    GLenum err = glewInit();
    if (err != GLEW_OK) {
        std::cerr << "Failed to initialize GLEW: " << glewGetErrorString(err) << std::endl;
        return false;
    }
    // Clear any errors generated by glewInit() (known issue)
    while(glGetError() != GL_NO_ERROR);

    // Print OpenGL version info
    std::cout << "OpenGL Context Info:" << std::endl;
    std::cout << "  Version: " << glGetString(GL_VERSION) << std::endl;
    std::cout << "  Vendor: " << glGetString(GL_VENDOR) << std::endl;
    std::cout << "  Renderer: " << glGetString(GL_RENDERER) << std::endl;
    std::cout << "  GLSL Version: " << glGetString(GL_SHADING_LANGUAGE_VERSION) << std::endl;
    
    // Check for minimum OpenGL version requirement (3.3)
    int major, minor;
    glGetIntegerv(GL_MAJOR_VERSION, &major);
    glGetIntegerv(GL_MINOR_VERSION, &minor);
    std::cout << "  Reported version: " << major << "." << minor << std::endl;
    
    if (major < 3 || (major == 3 && minor < 3)) {
        std::cerr << "ERROR: OpenGL 3.3 or higher is required, but " << major << "." << minor << " was detected." << std::endl;
        glfwTerminate();
        return false;
    }
    
    // Check for required OpenGL extensions
    bool hasTBO = glewIsSupported("GL_ARB_texture_buffer_object");
    std::cout << "  Texture Buffer Object support: " << (hasTBO ? "Yes" : "No") << std::endl;
    if (!hasTBO) {
        std::cerr << "WARNING: GL_ARB_texture_buffer_object not supported, TBO visualization may not work" << std::endl;
    }

    return true;
}

bool Application::initImGui() {
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    // io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard; // Enable Keyboard Controls
    // io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;  // Enable Gamepad Controls
    // io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;   // Disable Docking for now
    // io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable; // Disable Multi-Viewport for now

    ImGui::StyleColorsDark();
    
    // Tweak styles when viewports are enabled
    ImGuiStyle& style = ImGui::GetStyle();
    // if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) { // Disable check for now
    //     style.WindowRounding = 0.0f;
    //     style.Colors[ImGuiCol_WindowBg].w = 1.0f;
    // }

    // Enhance control responsiveness and visibility (copied from old main.cpp)
    style.FrameRounding = 3.0f;
    style.GrabRounding = 3.0f;
    style.FrameBorderSize = 1.0f;
    style.GrabMinSize = 20.0f;
    style.ItemSpacing = ImVec2(8, 4);
    style.ItemInnerSpacing = ImVec2(4, 4);
    style.IndentSpacing = 12.0f;
    style.ScrollbarSize = 14.0f;
    style.WindowRounding = 4.0f;
    style.ChildRounding = 2.0f;
    style.PopupRounding = 2.0f;
    style.Alpha = 0.95f; // Slightly more opaque
    style.DisabledAlpha = 0.6f;
    style.Colors[ImGuiCol_SliderGrab] = ImVec4(0.8f, 0.8f, 0.8f, 0.9f);
    style.Colors[ImGuiCol_SliderGrabActive] = ImVec4(0.9f, 0.9f, 0.9f, 1.0f);
    style.Colors[ImGuiCol_FrameBgHovered] = ImVec4(0.3f, 0.3f, 0.3f, 0.9f);
    style.Colors[ImGuiCol_FrameBgActive] = ImVec4(0.4f, 0.4f, 0.4f, 0.9f);

    if (!ImGui_ImplGlfw_InitForOpenGL(m_window, true)) return false;
    if (!ImGui_ImplOpenGL3_Init("#version 330")) return false;

    return true;
}

bool Application::initModules() {
    m_audioProcessor = new AudioProcessor();
    if (!m_audioProcessor->initialize(SAMPLE_RATE, FRAMES_PER_BUFFER, NUM_CHANNELS)) {
        std::cerr << "Failed to initialize audio processor" << std::endl;
        return false;
    }

    int initialWidth, initialHeight;
    glfwGetFramebufferSize(m_window, &initialWidth, &initialHeight);
    m_visualizer = new Visualizer(*m_audioProcessor);
    if (!m_visualizer->initialize(initialWidth, initialHeight, VisualizationStyle::BAR_GRAPH)) { 
        std::cerr << "Failed to initialize visualizer" << std::endl;
        delete m_audioProcessor; // Clean up previously allocated module
        return false;
    }

    m_uiManager = new UIManager(*m_audioProcessor, *m_visualizer);
    // No specific init needed for UIManager currently

    // Initialize NFD
    NFD_Init();

    return true;
}

// --- Main Initialization --- 

bool Application::initialize() {
    if (!initGLFW()) {
        return false;
    }

    if (!initImGui()) {
        return false;
    }

    if (!initModules()) {
        return false;
    }

    // Configure global OpenGL state
    glEnable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    
    // Clear color and depth
    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    
    // Make sure we're viewing the correct framebuffer
    glBindFramebuffer(GL_FRAMEBUFFER, 0);

    return true;
}

// --- Main Loop --- 

void Application::run() {
    while (!glfwWindowShouldClose(m_window)) {
        glfwPollEvents();

        // Start the Dear ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // Get current framebuffer size for rendering viewport
        int display_w, display_h;
        glfwGetFramebufferSize(m_window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);

        // Clear the background
        glClearColor(0.1f, 0.1f, 0.12f, 1.0f); // Slightly darker blueish background
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        // Render UI using the manager
        m_uiManager->render(m_window);

        // Render main visualization
        m_visualizer->render();

        // Render Dear ImGui
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        // Update and Render additional Platform Windows (for docking/viewports)
        // ImGuiIO& io = ImGui::GetIO(); // Already got io above
        // if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) { // Disable check for now
        //     GLFWwindow* backup_current_context = glfwGetCurrentContext();
        //     ImGui::UpdatePlatformWindows();
        //     ImGui::RenderPlatformWindowsDefault();
        //     glfwMakeContextCurrent(backup_current_context);
        // }

        glfwSwapBuffers(m_window);
    }
}

// --- Cleanup --- 

void Application::cleanup() {
    // Cleanup ImGui
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    if (ImGui::GetCurrentContext()) { // Check if context exists before destroying
        ImGui::DestroyContext();
    }

    // Deinitialize NFD
    NFD_Quit();

    // Cleanup modules (delete allocated memory)
    delete m_uiManager;
    m_uiManager = nullptr;
    delete m_visualizer;
    m_visualizer = nullptr;
    delete m_audioProcessor;
    m_audioProcessor = nullptr;

    // Cleanup GLFW
    if (m_window) {
        glfwDestroyWindow(m_window);
        m_window = nullptr;
    }
    glfwTerminate();
}

// --- Callback Handling --- 

// Static callback functions

void Application::framebuffer_size_callback_static(GLFWwindow* window, int width, int height) {
    Application* app = static_cast<Application*>(glfwGetWindowUserPointer(window));
    if (app) {
        app->framebuffer_size_callback(width, height);
    }
}

void Application::cursor_position_callback_static(GLFWwindow* window, double xpos, double ypos) {
    Application* app = static_cast<Application*>(glfwGetWindowUserPointer(window));
    // Forward event to Visualizer, but only if ImGui doesn't want the mouse
    ImGuiIO& io = ImGui::GetIO();
    if (app && app->m_visualizer && !io.WantCaptureMouse) {
        app->m_visualizer->handleMouseMove(xpos, ypos);
    }
}

void Application::mouse_button_callback_static(GLFWwindow* window, int button, int action, int mods) {
    Application* app = static_cast<Application*>(glfwGetWindowUserPointer(window));
    // Forward event to Visualizer if ImGui doesn't want the mouse
    ImGuiIO& io = ImGui::GetIO();
    if (app && app->m_visualizer && !io.WantCaptureMouse) {
        app->m_visualizer->handleMouseButton(button, action, mods);
    }
}

void Application::scroll_callback_static(GLFWwindow* window, double xoffset, double yoffset) {
    Application* app = static_cast<Application*>(glfwGetWindowUserPointer(window));
    // Forward event to Visualizer if ImGui doesn't want the mouse
    ImGuiIO& io = ImGui::GetIO();
    if (app && app->m_visualizer && !io.WantCaptureMouse) {
         app->m_visualizer->handleMouseScroll(xoffset, yoffset);
    }
}

// Instance member function to handle the resize
void Application::framebuffer_size_callback(int width, int height) {
    if (width > 0 && height > 0 && m_visualizer) {
        m_visualizer->resize(width, height);
    }
} 